version: "3.6"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${API_URL}
    image: spacex
    volumes:
      - ./src:/app/src
    ports:
      - "3001:3000"
